### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by zutotonno** [ZackAkil/video-intelligence-api-visualiser#8]
Hi Zack, 
can you please provide an installation guide or the VUE project with all the dependencies that you created when building this application?
When I pull your repo and launch index.html on my local pc, it does not work properly and it just plays the test video.

Thank you in advance

**Comment by ZackAkil** [comment]
Hi, @zutotonno, for this project I chose to build it [without using build tools](https://github.com/ZackAkil/compilerless-vue-component-dev), so in theory if you download all of the code and the folder structure remains the same, it should then just work and you can change the code as you see it in the repo, however you will need to run it as a localhost server, otherwise the local test json file won't load in due to a 'CORS' error.
